# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  contextmapimage:
    image: contextmapimage
    container_name: contextmapimage-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5125:5125
    environment:
    - "AZURE_CLIENT_ID=<your_client_id>"
    - "AZURE_TENANT_ID=<your_tenant_id>"
    - "AZURE_CLIENT_SECRET=<your_secret>"
    - "BLOB_STORAGE_URL=<your_blob_storage_url>"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
